make:
	gcc "EJ1.c" -o "EJ1";
	gcc "EJ1AP2U3.c" -o "EJ1AP23";
	gcc "EJ2.c" -o "EJ2" -lpthread;
	gcc "EJ2AP2.c" -o "EJ2AP2" -lpthread;
	gcc "EJ2AP4.c" -o "EJ2AP4" -lpthread;

run:
	./EJ1
	./EJ1AP23
	./EJ2AP2
	./EJ2
	./EJ2AP4


clean:
	rm EJ1 EJ1AP23 EJ2AP2 EJ2 EJ2AP4;
