; Listing generated by Microsoft (R) Optimizing Compiler Version 19.24.28316.0 

	TITLE	C:\Users\Anubis\Desktop\UA\UAADCProjects\Individual\Parte1\EjerciciosEnsamblador\Ejemplo1\Suma.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__D9A2886B_corecrt_stdio_config@h DB 01H
__FA4B997B_corecrt_wstdio@h DB 01H
__4C6EA709_stdio@h DB 01H
msvcjmc	ENDS
PUBLIC	__JustMyCode_Default
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
END
