# Elvi Mihai Sabau Sabau - 51254875L

OPTS = -Wall -O3 -std=c++0x

make: maxsumbt

maxsumbt: maxsum-bt.cc
	g++ ${OPTS} -o maxsum-bt maxsum-bt.cc 


tar: maxsum-bt.cc makefile
	tar cvfz ${ENV_VAR_DNI}.tar.gz  maxsum-bt.cc makefile