# Elvi Mihai Sabau Sabau - 51254875L

OPTS = -Wall -O3 -std=c++0x

make: maxsum

maxsum: maxsum.cc
	g++ ${OPTS} -o maxsum maxsum.cc 


tar: maxsum.cc makefile
	tar cvfz ${ENV_VAR_DNI}.tar.gz  maxsum.cc makefile