### Atracciones.
GET http://localhost:3003/atracciones
Content-Type: application/json

{}

### Usuarios.
GET http://localhost:3003/usuarios
Content-Type: application/json

{}

### logs.
GET http://localhost:3003/logs
Content-Type: application/json

{}

### Ciudades.
POST http://localhost:3003/ciudades:5
Content-Type: application/json

{}