# Elvi Mihai Sabau Sabau - 51254875L

OPTS = -Wall -O3 -std=c++0x

make: maxsumgreedy

maxsumgreedy: maxsum-greedy.cc
	g++ ${OPTS} -o maxsum-greedy maxsum-greedy.cc 


tar: maxsum-greedy.cc makefile
	tar cvfz ${ENV_VAR_DNI}.tar.gz  maxsum-greedy.cc makefile